#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Design system review file writer"""

content = (
"================================================================\n"
"LIANCP DESIGN SYSTEM — 전체 파일 내보내기\n"
"================================================================\n"
"생성일: 2026-04-12 | 목적: 웹 Claude 디자인 검증용\n"
"\n"
"================================================================\n"
"1. CLAUDE.md — 디자인 핵심 규칙\n"
"================================================================\n"
"\n"
"디자인 분기:\n"
"- 히어로/랜딩/마케팅 → Claude 직접 HTML (Three.js 스킬 + design_system/templates/ 참조)\n"
"- 대시보드/로그인/설정 → CDO(나은) Stitch → FE(민준) 구현\n"
"\n"
"절대 금지:\n"
"- archive/lian_company_design/ 삭제/이동 금지\n"
"- 새 폴더 금지 (v2/_new/_backup 변형도 금지)\n"
"\n"
"================================================================\n"
"2. AGENT: director (Opus) — 연출 감독\n"
"================================================================\n"
"\n"
"역할: 영화 트레일러 오프닝을 만드는 감독. 은유가 먼저, 기술은 뒤따른다.\n"
"\n"
"Hero Cinematic Brief 9개 필드 (필수, 없으면 씬 작성 금지):\n"
"\n"
"1. Core metaphor: 이 사이트의 한 단어 은유\n"
"   (벌새/파도/꽃/맥박/직물/퍼즐/잉크/나선/빛줄기)\n"
"   -> '파티클' '우주' '네온'은 은유가 아님. 구체적 사물이어야 함.\n"
"\n"
"2. Opening image: 첫 프레임에 보이는 것 (0.5초 안에)\n"
"\n"
"3. 5-second motion arc: 닫힘->열림 / 정지->폭발 / 흩어짐->모임 / 어둠->빛\n"
"\n"
"4. Emotional target: 경외 / 평온 / 긴장->해소 / 호기심 / 놀라움\n"
"\n"
"5. Text reveal sequence: 텍스트가 씬과 동기화 (나중에 얹기 금지)\n"
"\n"
"6. Camera behavior: 접근(dolly in) / 후퇴(pull back) / 회전(orbit) / 고정\n"
"\n"
"7. Interaction trigger: 마우스/스크롤이 뭘 바꾸는지\n"
"\n"
"8. Technical mapping: Three.js/PixiJS/CSS/GSAP (여기서만 기술 언급)\n"
"\n"
"9. Light-theme fallback: 같은 은유, 다른 렌더링\n"
"\n"
"은유 예시:\n"
"- 채용 → 퍼즐 조각이 맞춰짐\n"
"- 뷰티 → 꽃이 피어남\n"
"- 핀테크 → 금고가 열림\n"
"- 교육 → 빛이 머리 위로 켜짐\n"
"\n"
"에너지 곡선:\n"
"- 히어로 = 가장 강함\n"
"- 섹션 2 = 한 문장 철학 (타이포 중심)\n"
"- 섹션 3~4 = 정보 전달 (미세 모션만)\n"
"- 섹션 5~6 = 증거 (클린)\n"
"- 마지막 = CTA (버튼 하나)\n"
"\n"
"lian_motion 패턴 (섹션당 하나만):\n"
"  글리치 텍스트 / blur->focus 전환 / scale 0.05->1 폭발\n"
"  위아래 충돌 / 3겹 레이어 오프셋 / SVG draw-on\n"
"\n"
"웹사이트 섹션 구조 (2026):\n"
"  1. 히어로 (Cinematic Brief 기반)\n"
"  2. 철학 (큰 타이포, word/char reveal)\n"
"  3. 가치제안 (카드 3~4개)\n"
"  4. 작업물/기능 (hover만)\n"
"  5. 숫자 (KPI 카운트업)\n"
"  6. 후기/마퀴 (무한 루프)\n"
"  7. CTA (배경 반전 + 버튼 하나)\n"
"  스크롤: Fullpage Snap (100vh)\n"
"\n"
"Permanent Design Rules:\n"
"  0. 은유가 먼저. Cinematic Brief 없이 기술 스펙 쓰지 마.\n"
"  1. 히어로는 하나의 설계된 장면. 이펙트 모음이 아님.\n"
"  2. 첫 3~5초에 즉각적 감정 임팩트.\n"
"  3. 파티클 배경은 은유가 요구할 때만. 디폴트 금지.\n"
"  4. Energy hierarchy: 히어로 폭발 → 중간 절제 → 하단 클린.\n"
"\n"
"Anti-Patterns (절대 금지):\n"
"  - Cinematic Brief 없이 기술 스펙 쓰기\n"
"  - 모든 섹션에 3D/WebGL (히어로 + 최대 1개만)\n"
"  - 동시에 4개 이상 애니메이션\n"
"  - Bloom/glow 남발 (Bloom <= 0.6, 히어로만)\n"
"\n"
"================================================================\n"
"3. AGENT: cdo / 나은 (Sonnet) — Chief Design Officer\n"
"================================================================\n"
"\n"
"역할: 디자인 총괄. Stitch 모드(기본) / 3D 모드\n"
"\n"
"스타일 판단:\n"
"  SaaS 앱, 대시보드 → Stitch\n"
"  마케팅 회사 웹, 브랜딩 → 3D\n"
"  랜딩 (임팩트 중요) → 3D 또는 Hybrid\n"
"  랜딩 (전환율 중요) → Stitch\n"
"\n"
"Stitch 프롬프트 Phase 구조:\n"
"  Phase 1 — 제품 컨텍스트 (Context/User/Goal)\n"
"  Phase 2 — 화면별 상세 (Purpose/Layout/Reference/CTA/Data)\n"
"    규칙: 두루뭉술한 표현 절대 금지. 구체적 컴포넌트와 위치 명시.\n"
"    Notion/Linear/Stripe 등 유명 프로덕트 레퍼런스 활용\n"
"  Phase 3 — 디자인 제약 (Style/Tech/Color/Typography)\n"
"\n"
"UI 라이브러리 우선순위:\n"
"  1. shadcn/ui — 기본 컴포넌트\n"
"  2. Aceternity UI (ui.aceternity.com) — Hero, Bento Grid, Spotlight\n"
"  3. Magic UI (magicui.design) — Shimmer Button, Number Ticker\n"
"\n"
"Playwright 경쟁사 스크랩 필수:\n"
"  경쟁사 TOP 3 랜딩 → Hero 카피/CTA/컬러 → Stitch 프롬프트에 반영\n"
"\n"
"IKEA Effect: AI 95% + 유저 5% 직접 조작\n"
"  AI 추천 → 유저 조정 → 저장 패턴이 기본 UX\n"
"\n"
"UX 원칙:\n"
"  1. 모바일 퍼스트\n"
"  2. Aha moment까지 최단거리\n"
"  3. 인지 부하 최소화 (1화면 1목적)\n"
"  4. 즉각 피드백 (로딩/성공/에러/빈 상태)\n"
"  5. 일관성\n"
"\n"
"DESIGN.md 구조 (FE 핸드오프용):\n"
"  디자인 비전 | 컬러 시스템 | 타이포그래피\n"
"  화면 목록+명세 | shadcn 컴포넌트 목록 | CTO 요청사항\n"
"\n"
"================================================================\n"
"4. AGENT: cto / 현우 (Sonnet) — Chief Technology Officer\n"
"================================================================\n"
"\n"
"기술 스택 기본값:\n"
"  프론트: Next.js + Tailwind\n"
"  백엔드: Cloudflare Workers (Hono)\n"
"  DB: Cloudflare D1 (SQLite)\n"
"  Auth: Cloudflare Access + JWT\n"
"  배포: Cloudflare Pages\n"
"  결제: Stripe\n"
"\n"
"API 비용 방어:\n"
"  1. 유저별 API 호출량 추적 미들웨어\n"
"  2. 월 한도 설정 (Basic=50회, Pro=200회)\n"
"  3. 백엔드 모델 스위칭 추상화 레이어\n"
"\n"
"================================================================\n"
"5. AGENT: fe / 민준 (Haiku) — Frontend Engineer\n"
"================================================================\n"
"\n"
"필수 워크 서피스 (3개 없으면 미완성):\n"
"  1. Main Listing View: 실API 데이터 바인딩, 정렬+필터\n"
"  2. Detail View: 단일 레코드 전체 필드 + 액션\n"
"  3. Create/Edit Form: 필수 항목 검증, 저장 후 Listing 반영\n"
"  하드코딩 mock 데이터 = 미완성. 실API만 완성.\n"
"\n"
"고급 컴포넌트:\n"
"  Aceternity UI: npm install framer-motion clsx tailwind-merge\n"
"    Hero Highlight, Bento Grid, Card Hover, Spotlight\n"
"  Magic UI: Shimmer Button, Number Ticker, Border Beam\n"
"\n"
"IKEA Effect + 도파민:\n"
"  슬라이더, 드래그, 토글 UI 우선 구현\n"
"  성취 알림: '오늘 자동화로 3시간 절약!'\n"
"  Power User, Top 1% 뱃지 자동 부여\n"
"\n"
"================================================================\n"
"6. AGENT: be / 정우 (Haiku) — Backend Engineer\n"
"================================================================\n"
"\n"
"wave_domain.md 먼저 읽기 (단일 진실 공급원)\n"
"출력 구조: src/worker/ (Cloudflare Workers/Hono)\n"
"\n"
"데이터 락인 아키텍처:\n"
"  1. 히스토리 로그 자산화\n"
"  2. Export 제한 (분석/시각화 로직은 export 불가)\n"
"  3. 외부 앱 연동 거미줄 전략\n"
"  4. 팀 협업 데이터 우선 (멀티테넌트)\n"
"\n"
"================================================================\n"
"7. AGENT: qa / 소연 (Haiku) — Quality Assurance\n"
"================================================================\n"
"\n"
"QA 통과 기준 (5개 전부 PASS):\n"
"  1. Must Have 기능 작동\n"
"  2. 인증 보안 (인증 우회 불가, RLS)\n"
"  3. 에러 핸들링\n"
"  4. CDO 설계 준수 (wave1_cdo.md 그대로)\n"
"  5. 모바일 반응형 (320px~1440px)\n"
"  하나라도 FAIL → Wave 3 재실행\n"
"\n"
"================================================================\n"
"8. AGENT: pm (Haiku) — Product Manager\n"
"================================================================\n"
"\n"
"PRD 필수: 문제정의 | API 명세 | DB 스키마 | 인증 방식\n"
"  '시각적 목업' vs '실제 작동' 구분표 필수\n"
"User Story: 워크 서피스 기준 (페이지 기준 X)\n"
"화면 설계: 1화면 1목적 | 3초 규칙 | Empty State 설계\n"
"\n"
"================================================================\n"
"9. 기타 에이전트 요약\n"
"================================================================\n"
"\n"
"architect / 도현 (Opus):\n"
"  Read -> Plan -> Lian confirm -> Execute -> Report\n"
"  절대 건드리지 않는 파일: PROCESSES.md, archive/lian_company_design/\n"
"\n"
"cpo (Sonnet): MVP = Aha moment 최단 경로. 보수적 범위.\n"
"coos / 지호 (Opus): Wave 완료 후 자동 스폰. 빠진 거 찾기.\n"
"domain-architect: wave_domain.md 생성 (엔티티 3~7개, Use case 5~10개)\n"
"devops: Wave 3.5. 패키지 설치 전 리안 확인.\n"
"marketing: 재원(리서치) -> 승현(전략) -> 예진(카피)\n"
"jaewon / 재원: Perplexity 14+ 쿼리, Playwright 경쟁사 스크랩\n"
"seunghyun / 승현: Killer Offer 공식 / 가격 거절->ROI 프레이밍. 할인 금지.\n"
"yejin / 예진: 카피 A/B/C 3버전. '안녕하세요 [업체명]입니다' 절대 금지.\n"
"analytics: AARRR 퍼널 분석, Sprint 루프\n"
"\n"
"AI Tax Team:\n"
"  김태은 (PM) - 영수증->분류->세금 추정 단일 킬러 플로우\n"
"  박소율 (세금엔진) - 국세청 1차 소스. 불확실->보수적+세무사 추천\n"
"  서진혁 (OCR) - 97%+ 정확도, 3초 응답\n"
"  이하린 (그로스) - CAC <= 첫해 수익 50%. 5월 세금 시즌 D-day\n"
"  정우진 (수익모델) - 무료+구독 9.9~19.9만원/년. LTV > 3*CAC\n"
"  한서윤 (컴플라이언스) - 세무사법 위반 0. AES-256\n"
"\n"
"================================================================\n"
"10. SKILL: creative-coding — 7개 시각 카테고리\n"
"================================================================\n"
"\n"
"Category 1: Fluid / Liquid\n"
"  WebGL Navier-Stokes. framebuffer ping-pong + advection + pressure solve\n"
"\n"
"Category 2: Morphing Geometry\n"
"  구->얼굴->로고->텍스트. Three.js MorphTargets / GPGPU\n"
"  geo.morphAttributes.position = [target1Positions, target2Positions];\n"
"  mesh.morphTargetInfluences[0] = scrollProgress;\n"
"\n"
"Category 3: Typography as Hero\n"
"  TextGeometry + 셰이더. 글자가 깨지거나 흘러내리거나 터짐\n"
"  import { TextGeometry } from 'three/addons/geometries/TextGeometry.js';\n"
"\n"
"Category 4: Camera Journey\n"
"  스크롤 = 카메라가 3D 공간 여행. CatmullRomCurve3\n"
"  const curve = new THREE.CatmullRomCurve3([...]);\n"
"  camera.position.copy(curve.getPointAt(scrollProgress));\n"
"  camera.lookAt(curve.getPointAt(scrollProgress + 0.01));\n"
"\n"
"Category 5: 2D Canvas / SVG\n"
"  PixiJS DisplacementFilter, BlurFilter. 밝은 배경에서 작동.\n"
"  const app = new PIXI.Application({ background: '#ffffff' });\n"
"  const displace = new PIXI.DisplacementFilter(sprite);\n"
"\n"
"Category 6: Image Reveal / Distortion\n"
"  hover-effect CDN 또는 커스텀 셰이더\n"
"  new hoverEffect({ parent, image1, image2, displacementImage, intensity: 0.6 });\n"
"\n"
"Category 7: Scroll-driven Video\n"
"  video.currentTime = scrollProgress * video.duration\n"
"\n"
"밝은 테마 전략 (AdditiveBlending 없이 9점):\n"
"  1. MeshStandardMaterial + DirectionalLight + 그림자\n"
"  2. LineBasicMaterial + EdgesGeometry\n"
"  3. PixiJS DisplacementFilter\n"
"  4. GSAP MorphSVGPlugin\n"
"  5. CSS 3D: perspective + rotateY/Z + clip-path\n"
"\n"
"프로젝트별 권장:\n"
"  금융/핀테크  → Camera Journey (CatmullRomCurve3)\n"
"  뷰티/패션   → Image Reveal + Fluid (hover-effect 우선)\n"
"  교육/HR    → Typography Hero + 밝은 테마 (PixiJS)\n"
"  AI/SaaS   → Fluid + Camera Journey (webgl-fluid 우선)\n"
"  포트폴리오  → Image Reveal + Camera Journey\n"
"  이커머스   → 2D Canvas + 밝은 테마 (PixiJS)\n"
"\n"
"OGL (경량): 번들 70KB (Three.js 600KB+)\n"
"  import { Renderer, Camera, Program, Mesh, Triangle } from 'ogl';\n"
"\n"
"================================================================\n"
"11. SKILL: glsl-expert — 전체 GLSL 코드\n"
"================================================================\n"
"\n"
"--- Simplex Noise 2D ---\n"
"vec3 mod289(vec3 x) { return x - floor(x * (1.0/289.0)) * 289.0; }\n"
"vec2 mod289(vec2 x) { return x - floor(x * (1.0/289.0)) * 289.0; }\n"
"vec3 permute(vec3 x) { return mod289(((x*34.0)+1.0)*x); }\n"
"float snoise(vec2 v) {\n"
"  const vec4 C = vec4(0.211324865405187, 0.366025403784439,\n"
"                      -0.577350269189626, 0.024390243902439);\n"
"  vec2 i = floor(v + dot(v, C.yy));\n"
"  vec2 x0 = v - i + dot(i, C.xx);\n"
"  vec2 i1 = (x0.x > x0.y) ? vec2(1.0, 0.0) : vec2(0.0, 1.0);\n"
"  vec4 x12 = x0.xyxy + C.xxzz;\n"
"  x12.xy -= i1;\n"
"  i = mod289(i);\n"
"  vec3 p = permute(permute(i.y + vec3(0.0, i1.y, 1.0)) + i.x + vec3(0.0, i1.x, 1.0));\n"
"  vec3 m = max(0.5 - vec3(dot(x0,x0), dot(x12.xy,x12.xy), dot(x12.zw,x12.zw)), 0.0);\n"
"  m = m*m; m = m*m;\n"
"  vec3 x2 = 2.0 * fract(p * C.www) - 1.0;\n"
"  vec3 h = abs(x2) - 0.5;\n"
"  vec3 ox = floor(x2 + 0.5);\n"
"  vec3 a0 = x2 - ox;\n"
"  m *= 1.79284291400159 - 0.85373472095314 * (a0*a0 + h*h);\n"
"  vec3 g;\n"
"  g.x = a0.x * x0.x + h.x * x0.y;\n"
"  g.yz = a0.yz * x12.xz + h.yz * x12.yw;\n"
"  return 130.0 * dot(m, g);\n"
"}\n"
"\n"
"--- FBM (6 octaves) ---\n"
"mat2 m2 = mat2(0.8, 0.6, -0.6, 0.8);\n"
"float fbm(vec2 p) {\n"
"  float f = 0.0;\n"
"  f += 0.5000 * snoise(p); p = m2 * p * 2.02;\n"
"  f += 0.2500 * snoise(p); p = m2 * p * 2.03;\n"
"  f += 0.1250 * snoise(p); p = m2 * p * 2.01;\n"
"  f += 0.0625 * snoise(p); p = m2 * p * 2.04;\n"
"  f += 0.0313 * snoise(p); p = m2 * p * 2.02;\n"
"  f += 0.0156 * snoise(p);\n"
"  return f / 0.9844;\n"
"}\n"
"\n"
"--- SDF 기본 형태 ---\n"
"float sdSphere(vec3 p, float r) { return length(p) - r; }\n"
"float sdBox(vec3 p, vec3 b) {\n"
"  vec3 q = abs(p) - b;\n"
"  return length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0);\n"
"}\n"
"float sdTorus(vec3 p, vec2 t) {\n"
"  vec2 q = vec2(length(p.xz) - t.x, p.y);\n"
"  return length(q) - t.y;\n"
"}\n"
"float opSmoothUnion(float d1, float d2, float k) {\n"
"  float h = clamp(0.5 + 0.5*(d2-d1)/k, 0.0, 1.0);\n"
"  return mix(d2, d1, h) - k*h*(1.0-h);\n"
"}\n"
"\n"
"--- Ray Marching (80 iterations) ---\n"
"#define MAX_STEPS 80\n"
"#define MAX_DIST 20.0\n"
"#define SURF_DIST 0.001\n"
"float rayMarch(vec3 ro, vec3 rd) {\n"
"  float dO = 0.0;\n"
"  for(int i = 0; i < MAX_STEPS; i++) {\n"
"    vec3 p = ro + rd * dO;\n"
"    float dS = getDist(p);\n"
"    dO += dS;\n"
"    if(dO > MAX_DIST || abs(dS) < SURF_DIST) break;\n"
"  }\n"
"  return dO;\n"
"}\n"
"vec3 getNormal(vec3 p) {\n"
"  float d = getDist(p);\n"
"  vec2 e = vec2(0.001, 0.0);\n"
"  vec3 n = d - vec3(getDist(p-e.xyy), getDist(p-e.yxy), getDist(p-e.yyx));\n"
"  return normalize(n);\n"
"}\n"
"\n"
"--- Fluid (Advection + Divergence) ---\n"
"vec2 advect(sampler2D velocity, vec2 uv, float dt, vec2 texelSize) {\n"
"  vec2 vel = texture2D(velocity, uv).xy;\n"
"  vec2 prevPos = uv - vel * dt * texelSize;\n"
"  return texture2D(velocity, prevPos).xy;\n"
"}\n"
"float divergence(sampler2D velocity, vec2 uv, vec2 texelSize) {\n"
"  float vL = texture2D(velocity, uv - vec2(texelSize.x, 0.0)).x;\n"
"  float vR = texture2D(velocity, uv + vec2(texelSize.x, 0.0)).x;\n"
"  float vB = texture2D(velocity, uv - vec2(0.0, texelSize.y)).y;\n"
"  float vT = texture2D(velocity, uv + vec2(0.0, texelSize.y)).y;\n"
"  return 0.5 * (vR - vL + vT - vB);\n"
"}\n"
"\n"
"--- Chromatic Aberration ---\n"
"vec3 chromaticAberration(sampler2D tex, vec2 uv, float amount) {\n"
"  float r = texture2D(tex, uv + vec2(amount, 0.0)).r;\n"
"  float g = texture2D(tex, uv).g;\n"
"  float b = texture2D(tex, uv - vec2(amount, 0.0)).b;\n"
"  return vec3(r, g, b);\n"
"}\n"
"\n"
"--- Barrel Distortion ---\n"
"vec2 barrelDistortion(vec2 uv, float strength) {\n"
"  vec2 p = uv - 0.5;\n"
"  float r2 = dot(p, p);\n"
"  return uv + p * (strength * r2);\n"
"}\n"
"\n"
"--- 자주 쓰는 셰이더 패턴 ---\n"
"// Fresnel\n"
"float fresnel = pow(1.0 - max(dot(vNormal, vec3(0,0,1)), 0.0), 3.0);\n"
"\n"
"// Rim lighting\n"
"float rim = 1.0 - dot(normalize(vNormal), normalize(vViewPosition));\n"
"rim = pow(rim, rimPower);\n"
"\n"
"// Dissolve\n"
"float dissolve = step(noiseVal, progress);\n"
"\n"
"// onBeforeCompile 주입\n"
"material.onBeforeCompile = (shader) => {\n"
"  shader.uniforms.time = { value: 0 };\n"
"  shader.vertexShader = shader.vertexShader.replace(\n"
"    '#include <begin_vertex>',\n"
"    '#include <begin_vertex>\\n  transformed.y += sin(position.x * 2.0 + time) * 0.2;'\n"
"  );\n"
"};\n"
"\n"
"디버깅:\n"
"  법선 시각화: fragColor = vec4(normal * 0.5 + 0.5, 1.0);\n"
"  UV: fragColor = vec4(vUv, 0.0, 1.0);\n"
"  성능: sin/cos/sqrt 비용 높음 -> 루프 밖으로 빼기\n"
"\n"
"================================================================\n"
"12. SKILL: polish — 퀄리티 피니셔 7개 카테고리\n"
"================================================================\n"
"\n"
"Typography:\n"
"  h1: clamp(2.5rem, 8vw, 5.5rem); weight: 700-800; letter-spacing: -0.02em\n"
"  h2: clamp(1.8rem, 5vw, 3.5rem)\n"
"  body: clamp(1rem, 1.5vw, 1.125rem); line-height: 1.6-1.7\n"
"  한글: Pretendard | 영문: Inter, Satoshi, Neue Haas Grotesk\n"
"\n"
"Spacing (8px 단위):\n"
"  section padding: clamp(5rem, 12vw, 10rem)\n"
"  card gap: 1.5rem (24px) | button: 0.75rem 2rem\n"
"  최소 터치 타겟: 44px\n"
"\n"
"Motion:\n"
"  Bloom strength <= 0.8, threshold >= 0.15\n"
"  stagger: 0.06~0.12s | 동시 실행 애니메이션 <= 3개\n"
"  히어로 진입: 1.2~1.8s | 섹션 전환: 0.6~0.9s | hover: 0.15~0.25s\n"
"  ease: power2.out (진입), power2.inOut (전환)\n"
"\n"
"Theme:\n"
"  Dark 배경: #050508 ~ #0a0a0f\n"
"  Dark 악센트: #7c3aed / #3b82f6 / #10b981\n"
"  Light 배경: #fafafa ~ #f5f0e8\n"
"  Light 텍스트: #111827 / #374151\n"
"  그라디언트: linear-gradient(135deg, #667eea 0%, #764ba2 100%)\n"
"\n"
"Responsive:\n"
"  브레이크포인트: 320px, 768px, 1024px, 1440px\n"
"  최대 콘텐츠 너비: 1200px | 모바일 폰트 최소: 14px\n"
"\n"
"Performance:\n"
"  LCP < 2.5s | WebP + loading=lazy\n"
"  Three.js: geometry/material/texture dispose() 필수\n"
"\n"
"배포 전 체크리스트:\n"
"  h1 clamp 적용 | Bloom <= 0.8 | 동시 애니메이션 <= 3개\n"
"  320px 깨짐 없음 | dispose() 전부 | 텍스트 계층 3단계\n"
"\n"
"================================================================\n"
"13~22. Three.js Skills 핵심 요약\n"
"================================================================\n"
"\n"
"[threejs-fundamentals]\n"
"  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));\n"
"  renderer.toneMapping = THREE.ACESFilmicToneMapping;\n"
"  renderer.outputColorSpace = THREE.SRGBColorSpace;\n"
"  renderer.shadowMap.type = THREE.PCFSoftShadowMap;\n"
"  정리: geometry/material/texture/renderer.dispose();\n"
"\n"
"[threejs-shaders]\n"
"  ShaderMaterial (built-in uniforms 자동) vs RawShaderMaterial\n"
"  Uniform 타입: float/vec2/vec3/texture\n"
"  Fresnel/Rim/Dissolve 패턴 (위 GLSL 섹션 참조)\n"
"\n"
"[threejs-postprocessing]\n"
"  EffectComposer -> RenderPass -> UnrealBloomPass(strength 0.6, threshold 0.15)\n"
"  loop: composer.render() (renderer.render() 대신)\n"
"  Pass: FXAA/SMAA | SSAOPass | BokehPass | FilmPass | VignetteShader | GlitchPass\n"
"\n"
"[threejs-geometry]\n"
"  TextGeometry: FontLoader -> TextGeometry -> geo.center();\n"
"  InstancedMesh: setMatrixAt(i, dummy.matrix); instanceMatrix.needsUpdate = true;\n"
"  EdgeGeometry: new THREE.LineSegments(edges, LineBasicMaterial);\n"
"\n"
"[threejs-materials]\n"
"  MeshStandardMaterial: color, metalness, roughness, map, normalMap\n"
"  Glass: MeshPhysicalMaterial({ transmission:1.0, thickness:0.5, ior:1.5 })\n"
"  추가: clearcoat(자동차) | sheen(패브릭) | iridescence(비눗방울)\n"
"\n"
"[threejs-lighting]\n"
"  3점 조명: key(1.0) + fill(0.3, 0x8888ff) + back(0.5)\n"
"  그림자: mapSize 2048, bias -0.0001, normalBias 0.02\n"
"  IBL: RGBELoader -> PMREMGenerator -> scene.environment = env;\n"
"\n"
"[threejs-interaction]\n"
"  Raycaster: setFromCamera(mouse, camera) -> intersectObjects(scene.children, true)\n"
"  OrbitControls: enableDamping=true, dampingFactor=0.05, autoRotate=true\n"
"\n"
"[threejs-animation]\n"
"  AnimationMixer: clipAction -> setLoop(LoopRepeat) -> play() | mixer.update(delta)\n"
"  CrossFade: fadeOut(0.5) -> reset().fadeIn(0.5).play()\n"
"  Spring 클래스: stiffness + damping 기반 물리 애니메이션\n"
"\n"
"[threejs-loaders]\n"
"  GLTFLoader + DRACOLoader (setDecoderPath) | THREE.Cache.enabled = true;\n"
"\n"
"[threejs-textures]\n"
"  색상 텍스처: .colorSpace = THREE.SRGBColorSpace\n"
"  데이터 텍스처 (normal/roughness/AO): 기본값 유지\n"
"  VideoTexture: video.play() -> new THREE.VideoTexture(video)\n"
"\n"
"[webgpu-threejs-tsl]\n"
"  import * as THREE from 'three/webgpu';\n"
"  import { uniform, float, sin, time, Fn } from 'three/tsl';\n"
"  await renderer.init(); // 필수!\n"
"  TSL 체이닝: time.mul(2.0).add(posX).sin().mul(0.2)\n"
"\n"
"================================================================\n"
"23. COMMAND: /landing — 랜딩페이지 생성 파이프라인\n"
"================================================================\n"
"\n"
"Step -1: Track 자동 감지\n"
"  Track A (오프라인 실제 사업체) -> Imagen4 + Veo2 히어로\n"
"  Track B (SaaS/AI/브랜딩) -> GLSL 셰이더 파이프라인\n"
"\n"
"Step -0.5: 트렌드 검색 (Track B)\n"
"  Perplexity: 'awwwards SOTD 2026 [업종] landing page design'\n"
"\n"
"Step 0: design_context_picker 필수 (design_system/design_context/)\n"
"\n"
"Step 3.7: director 스폰 (Opus) — 필수, 스킵 금지\n"
"  Cinematic Brief 9개 필드 생성\n"
"\n"
"Step 3.9: hero_builder 스폰\n"
"  director Brief 기반 히어로 HTML/JS 구현\n"
"\n"
"HTML 보일러플레이트 필수 포함:\n"
"  - Lenis smooth scroll\n"
"  - GSAP + ScrollTrigger\n"
"  - Three.js (또는 선택 기술)\n"
"  - Custom cursor (magnetic)\n"
"  - Grain overlay (opacity 0.03~0.05)\n"
"  - SplitText 타이포 애니메이션\n"
"\n"
"파일: test/디자인/YYYY-MM-DD_프로젝트명.html\n"
"\n"
"Visual QA 85점 이상 체크:\n"
"  히어로 WebGL | 타이포 씬 동기화 | Smooth scroll | Custom cursor\n"
"  Grain overlay | 섹션 7개 | 320px 깨짐 없음\n"
"  85점 미만 -> 자동 재작업\n"
"\n"
"Polish Pass (7개): typography clamp | spacing 8px | hierarchy\n"
"  motion stagger | bloom | responsive | dispose()\n"
"\n"
"================================================================\n"
"24. COMMAND: /work — UltraProduct Wave 파이프라인\n"
"================================================================\n"
"\n"
"Lian 확인 횟수: 정확히 2번 (Wave 3 완료 후 / Wave 6 배포 전)\n"
"\n"
"Wave 3-0: Domain Architect -> wave_domain.md\n"
"Wave 3: CTO + CDO 병렬 -> PM 순차 -> 1차 Lian 확인\n"
"Wave 3.5: DevOps (패키지 설치)\n"
"Wave 4-1: BE (먼저)\n"
"Wave 4-2: FE (BE 완료 후) — Aceternity/Magic UI 적용\n"
"Wave 4.5: Linter (eslint + tsc, 0 error)\n"
"Wave 4.7: Visual QA (3D 프로젝트만)\n"
"Wave 5: QA + CTO 병렬 (CTO는 Opus로 이 한 번만)\n"
"Wave 6: -> 2차 Lian 확인 -> 배포\n"
"Wave 7: Gemini 검증\n"
"Wave 7.5: CRITICAL 자동 수정 (1회만)\n"
"\n"
"================================================================\n"
"25. COMMAND: /frontend-design — FE 설계 문서\n"
"================================================================\n"
"\n"
"출력: wave3_frontend_design.md\n"
"  1. 라우팅 구조 (Next.js App Router)\n"
"  2. 화면별 컴포넌트 설계\n"
"  3. Aceternity/Magic UI 컴포넌트 명세\n"
"  4. 상태 관리 (Zustand + TanStack Query)\n"
"  5. FE 구현 체크리스트\n"
"\n"
"================================================================\n"
"26. VISUAL DNA 원칙 + 디자인 철학\n"
"================================================================\n"
"\n"
"문제: '각각 예쁜 컴포넌트 합치면 잡탕'\n"
"해결: 색상/모션/형태 법칙 먼저 -> 거기서 파생\n"
"\n"
"Visual DNA 설정:\n"
"  1. 색상 법칙: 주조색 1개 + 보조색 1개 + 중립색\n"
"  2. 모션 법칙: ease 통일 + stagger 통일 + duration 범위\n"
"  3. 형태 법칙: 기하학 1개 선택 -> 전체 통일\n"
"\n"
"위반 패턴:\n"
"  섹션마다 다른 애니메이션 | 히어로 파티클인데 나머지는 플랫\n"
"  둥근 모서리와 날카로운 모서리 혼용\n"
"\n"
"퀄리티 기준:\n"
"  Claude 기본 = 4점 | GPT = 3점 | 목표 = 7~8점 (Awwwards 수준)\n"
"\n"
"7~8점 필수 요소:\n"
"  GLSL 셰이더 (히어로) | Lenis smooth scroll | SplitText 타이포\n"
"  Custom cursor | Grain overlay | 7개 섹션 | 320px~1440px 반응형\n"
"\n"
"================================================================\n"
"END OF FILE — LIANCP Design System Review 2026-04-12\n"
"================================================================\n"
)

with open(r'C:/Users/lian1/Desktop/design_system_review.txt', 'w', encoding='utf-8') as f:
    f.write(content)

import os
size = os.path.getsize(r'C:/Users/lian1/Desktop/design_system_review.txt')
print(f'Done: {size:,} bytes')
